const { ChatInputCommand } = require('../../classes/Commands');
const { EmbedBuilder } = require('discord.js');
const OpenAIManager = require('../../handlers/openai/OpenAIManager');

module.exports = new ChatInputCommand({
    global: true,
    aliases: ['chat'],
    cooldown: {
        type: 'user',
        usages: 2,
        duration: 10,
    },
    clientPerms: ['EmbedLinks'],
    data: {
        description: 'Ask Emris a question or give a prompt.',
        options: [{
            type: 3,
            name: 'prompt',
            description: 'The question or prompt for Emris',
            required: true,
        }, ],
    },
    run: async (client, interaction) => {
        const prompt = interaction.options.getString('prompt');
        await interaction.deferReply();
        const systemContent = 'Welcome adventurer! As a Runescape chatbot, I am here to assist you in your journey through Gielinor. Whether you need help finding a particular item, leveling up a skill, or completing a quest, I am at your service. Feel free to ask me anything Runescape-related, and I will do my best to provide you with accurate and helpful information. Dont forget to join our Runescape community here on Discord, where you can connect with fellow players, share your achievements, and receive valuable tips and advice. Lets explore the world of Runescape together!';
        const aiResponse = await OpenAIManager.getGPTResponse(prompt, systemContent);
    
        const embed = new EmbedBuilder()
            .setTitle('GPT-4 Response')
            .setDescription(aiResponse)
            .setColor(0x00ff00)
            .setTimestamp()
            .setFooter({
                text: `Trained on data up until 9/2021 | Generated by ${client.user.username}`
            });
    
        await interaction.editReply({
            embeds: [embed]
        });
    },    
});